os:
  - linux

language: node_js

node_js: "8"

branches:
  only:
  - master

before_script:
  - nvm install 8.9.1
  - yarn install
  - yarn global add codecov

cache:
  directories:
    - node_modules
  yarn: true

script:
  - yarn test

after_success:
  - codecov
